### PR TITLE
Add Domino::Form for easily reading and editing forms

### PR DESCRIPTION
**Pull request by shekibobo**
This adds the `Domino::Form` class as a subclass of `Domino`. It provides a few features to make reading/writing forms more fluent.

```html
<html>
  <body>
    <h1>Edit Person</h1>

    <form action="/person/23" method="post" class="person">
      <div class="input name">
        <label for="person_name">First Name</label>
        <input type="text" id="person_name" name="person[name]" value="Alice" />
      </div>

      <div class="input last_name">
        <label for="person_name">Last Name</label>
        <input type="text" id="person_last_name" name="person[last_name]" value="Cooper" />
      </div>

      <div class="input bio">
        <label for="person_bio">Biography</label>
        <textarea id="person_bio" name="person[bio]">Alice is fun</textarea>
      </div>

      <div class="input fav_color">
        <label for="person_fav_color">Favorite Color</label>
        <select id="person_fav_color" name="person[fav_color]">
          <option val="red">Red</option>
          <option val="blue" selected>Blue</option>
          <option val="green">Green</option>
        </select>
      </div>

      <div class="input age">
        <label for="person_age">Biography</label>
        <input type="number" min="0" step="1" id="person_age" name="person[age]" value="23" />
      </div>

      <div class="input is_human">
        <input type="hidden" name="is_human" value="0">
        <label for="is_human">
          <input id="is_human" type="checkbox" name="is_human" value="1">
          I'm a human
        </label>
      </div>

      <div class="input vehicles">
        <label for="person_vehicles_bike"><input id="person_vehicles_bike" type="checkbox" name="person[vehicles][]" value="Bike">Bike</label>
        <label for="person_vehicles_car"><input id="person_vehicles_car" type="checkbox" name="person[vehicles][]" value="Car">Car</label>
      </div>

      <div class="actions">
        <input type="submit" name="commit" value="Update Person" />
      </div>
    </form>
  </body>
</html>
```

Given the above form, you can create a `PersonForm`:

```ruby
module Dom
  class CheckBoxesField < Domino::Form::Field
    def read(node)
      node.find(locator).all('input[type=checkbox]').select(&:checked?).map(&:value)
    end

    def write(node, value)
      value = Array(value)
      node.find(locator).all('input[type=checkbox]').each do |box|
        box.set(value.include?(box.value))
      end
    end
  end

  class PersonForm < Domino::Form
    selector 'form.person'
    key 'person'

    field :name, 'First Name'
    field :last_name
    field :biography, 'person[bio]'
    field :favorite_color, 'Favorite Color', as: :select
    field :age, 'person_age'
    field :vehicles, '.input.vehicles', as: CheckBoxesField
    field :is_human, 'is_human', as: :boolean
  end
end
```

You can easily handle the common cases of text fields, selects, and boolean fields (checked/unchecked). You can also create a custom field type and override the `read` and `write` methods to easily extend your form to work with Chosen or Select2 forms or other field sets/types.

## Breaking Changes

- Remove support for Ruby 1.9.3 (EOL in 2015)

## Major Source Changes

- Refactored each class into its own file, and each support class (i.e. `Form`, `Form::Field` and its subclasses) are required by the class that needs it to make source more readable.
- Extracted the test helper that sets up basic requirements to run the test suite.
- Extracted the `TestApplication` and refactored to support an index page, and an edit/update page.
- Separated test files for `Domino` proper and `Domino::Form` so they don't get too overwhelming to read or modify.

### CODE REVIEW

**Comment by ngauthier** [comment]
request me as a reviewer when this is ready

**Comment by shekibobo** [comment]
@ngauthier Looks like I can't assign a reviewer, but I think I'm done.

Verified support for `<select multiple="multiple">` and basic attributes on forms. Let me know if you see any issues or edge cases you'd like me to add tests for.

**Comment by ngauthier** [comment]
Looks great, but could you add test coverage for form's create and update?

**Comment by shekibobo** [comment]
@ngauthier Added test coverage and fixed a few bugs I picked up along the way.

- `SelectField` no longer needs to be told if it's multiple, and you can set by option value or option text.
- `SelectField` yields each selected option node to the callback, so it can be overridden to use `&:text` or any normal callback, but instead of text, you get the node itself.
- Added some documentation around some of the methods.

**Comment by ngauthier** [comment]
Awesome! One more and I'm giving you commit rights 😄

**Comment by ngauthier** [comment]
0.9.0 is released

**Pull request merged**
